// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package subscription.proxies;

public class FoodPreference extends subscription.proxies.Enumeration
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Subscription.FoodPreference";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Order("Order"),
		Code("Code"),
		Name("Name"),
		Person_FoodPreference("Subscription.Person_FoodPreference");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FoodPreference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Subscription.FoodPreference"));
	}

	protected FoodPreference(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject foodPreferenceMendixObject)
	{
		super(context, foodPreferenceMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Subscription.FoodPreference", foodPreferenceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Subscription.FoodPreference");
	}

	/**
	 * @deprecated Use 'FoodPreference.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static subscription.proxies.FoodPreference initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return subscription.proxies.FoodPreference.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static subscription.proxies.FoodPreference initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new subscription.proxies.FoodPreference(context, mendixObject);
	}

	public static subscription.proxies.FoodPreference load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return subscription.proxies.FoodPreference.initialize(context, mendixObject);
	}

	public static java.util.List<subscription.proxies.FoodPreference> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<subscription.proxies.FoodPreference> result = new java.util.ArrayList<subscription.proxies.FoodPreference>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Subscription.FoodPreference" + xpathConstraint))
			result.add(subscription.proxies.FoodPreference.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Person_FoodPreference
	 */
	public final java.util.List<subscription.proxies.Person> getPerson_FoodPreference() throws com.mendix.core.CoreException
	{
		return getPerson_FoodPreference(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_FoodPreference
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<subscription.proxies.Person> getPerson_FoodPreference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<subscription.proxies.Person> result = new java.util.ArrayList<subscription.proxies.Person>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Person_FoodPreference.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(subscription.proxies.Person.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Person_FoodPreference
	 * @param person_foodpreference
	 */
	public final void setPerson_FoodPreference(java.util.List<subscription.proxies.Person> person_foodpreference)
	{
		setPerson_FoodPreference(getContext(), person_foodpreference);
	}

	/**
	 * Set value of Person_FoodPreference
	 * @param context
	 * @param person_foodpreference
	 */
	public final void setPerson_FoodPreference(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<subscription.proxies.Person> person_foodpreference)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (subscription.proxies.Person proxyObject : person_foodpreference)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Person_FoodPreference.toString(), identifiers);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final subscription.proxies.FoodPreference that = (subscription.proxies.FoodPreference) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Subscription.FoodPreference";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
