// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package localeswitcher.proxies;

public enum RecommendedChange
{
	Language(new java.lang.String[][] { new java.lang.String[] { "en_US", "Language" }, new java.lang.String[] { "ja_JP", "言語" }, new java.lang.String[] { "nl_NL", "Taal" }, new java.lang.String[] { "en_GB", "Language" }, new java.lang.String[] { "en_ZA", "Language" }, new java.lang.String[] { "en_CA", "Language" } }),
	TimeZone(new java.lang.String[][] { new java.lang.String[] { "en_US", "TimeZone" }, new java.lang.String[] { "ja_JP", "タイムゾーン" }, new java.lang.String[] { "nl_NL", "Tijdzone" }, new java.lang.String[] { "en_GB", "TimeZone" }, new java.lang.String[] { "en_ZA", "TimeZone" }, new java.lang.String[] { "en_CA", "TimeZone" } }),
	BothLanguageAndTimzone(new java.lang.String[][] { new java.lang.String[] { "en_US", "BothLanguageAndTimZone" }, new java.lang.String[] { "ja_JP", "言語とタイムゾーンの両方" }, new java.lang.String[] { "nl_NL", "Taal en tijdzone" }, new java.lang.String[] { "en_GB", "BothLanguageAndTimZone" }, new java.lang.String[] { "en_ZA", "BothLanguageAndTimZone" }, new java.lang.String[] { "en_CA", "BothLanguageAndTimZone" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private RecommendedChange(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
